# Generated by Django 4.2.7 on 2023-11-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='metainformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Applicant_name', models.CharField(max_length=50)),
                ('Deceased_name', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Contact_number', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=255)),
                ('Deceased_address', models.CharField(max_length=255)),
                ('Date', models.DateField()),
                ('Date_of_death', models.DateField()),
                ('time_of_death', models.TimeField()),
                ('Cause_of_death', models.CharField(max_length=255)),
                ('Relationship', models.CharField(max_length=50)),
                ('Form_number', models.IntegerField()),
                ('Amount', models.IntegerField()),
            ],
            options={
                'db_table': 'Person_Information',
            },
        ),
    ]
