# Generated by Django 4.2.3 on 2024-02-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamatulmsl', '0003_metainformation_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='metainformation',
            name='Aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='metainformation',
            name='Death_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='metainformation',
            name='Other_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
