# Generated by Django 4.2.3 on 2024-02-08 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamatulmsl', '0004_metainformation_aadhar_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metainformation',
            name='Death_certificate',
        ),
        migrations.RemoveField(
            model_name='metainformation',
            name='Other_file',
        ),
    ]
