# Generated by Django 4.2.3 on 2024-02-08 10:11

from django.db import migrations, models
import functools
import jamatulmsl.models


class Migration(migrations.Migration):

    dependencies = [
        ('jamatulmsl', '0005_remove_metainformation_death_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metainformation',
            name='Aadhar_card',
            field=models.FileField(blank=True, help_text='Browse a photo', null=True, upload_to=functools.partial(jamatulmsl.models.aadharcard, *(), **{'thumbnail': True})),
        ),
    ]
