# Generated by Django 4.2.3 on 2024-02-08 10:40

from django.db import migrations, models
import functools
import jamatulmsl.models


class Migration(migrations.Migration):

    dependencies = [
        ('jamatulmsl', '0006_alter_metainformation_aadhar_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='metainformation',
            name='Death_certificate',
            field=models.FileField(blank=True, help_text='Browse a photo', null=True, upload_to=functools.partial(jamatulmsl.models.deathcertificate, *(), **{'thumbnail': True})),
        ),
        migrations.AddField(
            model_name='metainformation',
            name='Other_file',
            field=models.FileField(blank=True, help_text='Browse a photo', null=True, upload_to=functools.partial(jamatulmsl.models.otherfile, *(), **{'thumbnail': True})),
        ),
    ]
