# Generated by Django 4.2.3 on 2024-02-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamatulmsl', '0007_metainformation_death_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metainformation',
            name='Deceased_age',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
